#!/usr/bin/env bash

readonly HAPROXY=/usr/sbin/haproxy
readonly HAPROXY_BASENAME=haproxy
readonly HAPROXY_CONFIG=/etc/haproxy/haproxy.cfg
readonly HAPROXY_BOOTSTRAP_LOCK_FILE=/var/lock/subsys/haproxy-bootstrap
readonly NICE=/bin/nice
readonly PID_PATH=/run/haproxy.pid

BLOCKER_PID=""
DAEMON_OPTS="
 -W
 -f ${HAPROXY_CONFIG}
 -p ${PID_PATH}
"
NICENESS=${HAPROXY_NICENESS:-10}

function __is_valid_configuration ()
{
	${HAPROXY} \
		-c \
		-q \
		-f ${HAPROXY_CONFIG}

	if [[ ${?} -ne 0 ]]; then
		printf -- \
			'Errors in configuration file.\n' \
			"${HAPROXY_BASENAME}" >&2
		return 1
	fi

	return 0
}

while true; do
	sleep 0.1
	[[ -e ${HAPROXY_BOOTSTRAP_LOCK_FILE} ]] || break
done

if ! __is_valid_configuration; then
	return 1
else
	exec ${NICE} \
		-n ${NICENESS} \
		${HAPROXY} \
		${DAEMON_OPTS}
fi
