#!/usr/bin/env bash

RSYSLOGD=/usr/sbin/rsyslogd
NICE=/bin/nice
SYSCTL=/usr/sbin/sysctl
DAEMON_OPTS=""

if [[ ! -f /usr/sbin/rsyslogd ]] \
	&& [[ -f /sbin/rsyslogd ]]; then
	RSYSLOGD=/sbin/rsyslogd
	DAEMON_OPTS+=" -c5"
fi

DAEMON_OPTS+="
 -n
 -4
 -Q
 -l 127.0.0.1
 -f /etc/rsyslog.conf
"

NICENESS=${RSYSLOGD_NICENESS:-10}

exec ${NICE} \
	-n ${NICENESS} \
	${RSYSLOGD} \
	${DAEMON_OPTS}