#!/usr/bin/env bash

readonly NICE=/bin/nice

DAEMON_OPTS=""
NICENESS=${RSYSLOGD_NICENESS:-10}

if [[ ! -f /usr/sbin/rsyslogd ]] \
	&& [[ -f /sbin/rsyslogd ]]; then
	readonly RSYSLOGD=/sbin/rsyslogd
	DAEMON_OPTS+=" -c5"
else
	readonly RSYSLOGD=/usr/sbin/rsyslogd
fi

DAEMON_OPTS+="
 -n
 -4
 -Q
 -l 127.0.0.1
 -f /etc/rsyslog.conf
"

exec ${NICE} \
	-n ${NICENESS} \
	${RSYSLOGD} \
	${DAEMON_OPTS}
