#!/usr/bin/env bash

readonly NICE="/bin/nice"
readonly NICENESS="10"

OPTIONS=""

if [[ ! -f /usr/sbin/rsyslogd ]] \
	&& [[ -f /sbin/rsyslogd ]]
then
	readonly BIN="/sbin/rsyslogd"
	OPTIONS+=" -c5"
else
	readonly BIN="/usr/sbin/rsyslogd"
fi

OPTIONS+="
 -n
 -4
 -Q
 -l 127.0.0.1
 -f /etc/rsyslog.conf
"

exec ${NICE} \
	-n ${NICENESS} \
	${BIN} \
	${OPTIONS}
