
# Common parameters of create and run targets
define DOCKER_CONTAINER_PARAMETERS
-t \
--privileged \
--name $(DOCKER_NAME) \
--publish $(DOCKER_PORT_MAP_TCP_80):80 \
--publish $(DOCKER_PORT_MAP_TCP_442):442 \
--publish $(DOCKER_PORT_MAP_TCP_443):443 \
--restart $(DOCKER_RESTART_POLICY) \
--env "HAPROXY_CONFIG=$(HAPROXY_CONFIG)" \
--env "HAPROXY_SERVER_ADDRESS_1=$(HAPROXY_SERVER_ADDRESS_1)" \
--env "HAPROXY_SERVER_ADDRESS_2=$(HAPROXY_SERVER_ADDRESS_2)" \
--env "HAPROXY_SERVER_ADDRESS_3=$(HAPROXY_SERVER_ADDRESS_3)" \
--env "HAPROXY_SERVER_ADDRESS_4=$(HAPROXY_SERVER_ADDRESS_4)"
endef

define DOCKER_CONTAINER_PARAMETERS_FULL
-t \
--privileged \
--name $(DOCKER_NAME) \
--publish $(DOCKER_PORT_MAP_TCP_22):22 \
--publish $(DOCKER_PORT_MAP_TCP_80):80 \
--publish $(DOCKER_PORT_MAP_TCP_442):442 \
--publish $(DOCKER_PORT_MAP_TCP_443):443 \
--restart $(DOCKER_RESTART_POLICY) \
--env "HAPROXY_CONFIG=$(HAPROXY_CONFIG)" \
--env "HAPROXY_SERVER_ADDRESS_1=$(HAPROXY_SERVER_ADDRESS_1)" \
--env "HAPROXY_SERVER_ADDRESS_2=$(HAPROXY_SERVER_ADDRESS_2)" \
--env "HAPROXY_SERVER_ADDRESS_3=$(HAPROXY_SERVER_ADDRESS_3)" \
--env "HAPROXY_SERVER_ADDRESS_4=$(HAPROXY_SERVER_ADDRESS_4)"
--env "SSH_AUTHORIZED_KEYS=$(SSH_AUTHORIZED_KEYS)" \
--env "SSH_AUTOSTART_SSHD=$(SSH_AUTOSTART_SSHD)" \
--env "SSH_AUTOSTART_SSHD_BOOTSTRAP=$(SSH_AUTOSTART_SSHD_BOOTSTRAP)" \
--env "SSH_CHROOT_DIRECTORY=$(SSH_CHROOT_DIRECTORY)" \
--env "SSH_INHERIT_ENVIRONMENT=$(SSH_INHERIT_ENVIRONMENT)" \
--env "SSH_SUDO=$(SSH_SUDO)" \
--env "SSH_USER=$(SSH_USER)" \
--env "SSH_USER_FORCE_SFTP=$(SSH_USER_FORCE_SFTP)" \
--env "SSH_USER_HOME=$(SSH_USER_HOME)" \
--env "SSH_USER_PASSWORD=$(SSH_USER_PASSWORD)" \
--env "SSH_USER_PASSWORD_HASHED=$(SSH_USER_PASSWORD_HASHED)" \
--env "SSH_USER_SHELL=$(SSH_USER_SHELL)" \
--env "SSH_USER_ID=$(SSH_USER_ID)"
endef
