# ------------------------------------------------------------------------------
# Ref: https://docs.docker.com/compose/compose-file/
#
# Setup:
# docker-compose -f docker-compose.yml -f docker-compose-h2.yml build
# docker-compose -f docker-compose.yml -f docker-compose-h2.yml down
#
# Run HTTP/2 example:
# docker-compose -f docker-compose.yml -f docker-compose-h2.yml up -d
#
# HATop usage:
# docker-compose exec haproxy hatop --help
# docker-compose exec haproxy hatop -s /var/lib/haproxy/stats-1 -i 1
# docker-compose exec haproxy hatop -s /var/lib/haproxy/stats-2 -i 1
# docker-compose exec haproxy hatop -s /var/lib/haproxy/stats-3 -i 1
# docker-compose exec haproxy hatop -s /var/lib/haproxy/stats-4 -i 1
# ------------------------------------------------------------------------------
version: "3.0"
services:
  haproxy:
    environment:
      HAPROXY_CONFIG: "/etc/haproxy/haproxy-h2.cfg"
