# ------------------------------------------------------------------------------
# Ref: https://docs.docker.com/compose/compose-file/
# 
# docker-compose -p p1 down
# docker-compose -p p1 up -d
# ------------------------------------------------------------------------------
version: "3.0"
networks:
  tier1:
    driver: "bridge"
  tier2:
    driver: "bridge"
    internal: true
services:
  haproxy:
    image: "jdeathe/centos-ssh-haproxy:latest"
    environment:
      HAPROXY_SSL_CERTIFICATE: "${HAPROXY_SSL_CERTIFICATE:-/var/run/secrets/haproxy_ssl_certificate}"
      HAPROXY_CONFIG: "/etc/haproxy/haproxy-http.cfg"
      HAPROXY_HOST_NAMES: "www.app.local app.local localhost.localdomain"
    networks:
      - "tier1"
      - "tier2"
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    sysctls:
      net.core.somaxconn: "32768"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
    tty: true
    ulimits:
      memlock: 82000
      nofile:
        soft: 524288
        hard: 1048576
      nproc: 65535
    volumes:
      # Emulate docker swarm secrets
      - "${PWD}/test/fixture/secrets:/var/run/secrets:ro"
  httpd_1:
    environment:
      APACHE_MOD_SSL_ENABLED: "false"
      APACHE_MPM: "event"
      APACHE_SERVER_ALIAS: "app.local"
      APACHE_SERVER_NAME: "www.app.local"
      PHP_OPTIONS_SESSION_SAVE_HANDLER: "memcached"
      PHP_OPTIONS_SESSION_SAVE_PATH: "memcached:11211"
    image: "jdeathe/centos-ssh-apache-php:2.2.5"
    networks:
      tier2:
        aliases:
          - "httpd_1"
          - "web_1"
    restart: "always"
    sysctls:
      net.core.somaxconn: "2048"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
  httpd_2:
    environment:
      APACHE_MOD_SSL_ENABLED: "false"
      APACHE_MPM: "event"
      APACHE_SERVER_ALIAS: "app.local"
      APACHE_SERVER_NAME: "www.app.local"
      PHP_OPTIONS_SESSION_SAVE_HANDLER: "memcached"
      PHP_OPTIONS_SESSION_SAVE_PATH: "memcached:11211"
    image: "jdeathe/centos-ssh-apache-php:2.2.5"
    networks:
      tier2:
        aliases:
          - "httpd_2"
          - "web_2"
    restart: "always"
    sysctls:
      net.core.somaxconn: "2048"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
  memcached:
    image: "jdeathe/centos-ssh-memcached:1.1.3"
    environment:
      MEMCACHED_CACHESIZE: "32"
      MEMCACHED_MAXCONN: "2048"
    networks:
      - "tier2"
    restart: "always"
    sysctls:
      net.core.somaxconn: "2048"