# ------------------------------------------------------------------------------
# Ref: https://docs.docker.com/compose/compose-file/
# 
# docker-compose -p p1 down
# docker-compose -p p1 up -d
# ------------------------------------------------------------------------------
version: "3.0"
networks:
  tier1:
    driver: "bridge"
  tier2:
    driver: "bridge"
    internal: true
services:
  haproxy:
    image: "jdeathe/centos-ssh-haproxy:latest"
    environment:
      HAPROXY_CERTIFICATE: "${HAPROXY_CERTIFICATE}"
      HAPROXY_CONFIG: "/etc/haproxy/haproxy-http.cfg"
      HAPROXY_HOST_NAMES: "www.app.local app.local localhost.localdomain"
    networks:
      - "tier1"
      - "tier2"
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    sysctls:
      net.core.somaxconn: "32768"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
    tty: true
    ulimits:
      memlock: 82000
      nofile:
        soft: 524288
        hard: 1048576
      nproc: 65535
  httpd_1:
    environment:
      APACHE_MOD_SSL_ENABLED: "false"
      APACHE_MPM: "event"
      APACHE_SERVER_ALIAS: "www.app"
      APACHE_SERVER_NAME: "www.app.local"
    image: "jdeathe/centos-ssh-apache-php:2.2.1"
    networks:
      tier2:
        aliases:
          - "httpd_1"
          - "web_1"
    restart: "always"
    sysctls:
      net.core.somaxconn: "2048"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
  httpd_2:
    environment:
      APACHE_MOD_SSL_ENABLED: "false"
      APACHE_MPM: "event"
      APACHE_SERVER_ALIAS: "www.app"
      APACHE_SERVER_NAME: "www.app.local"
    image: "jdeathe/centos-ssh-apache-php:2.2.1"
    networks:
      tier2:
        aliases:
          - "httpd_2"
          - "web_2"
    restart: "always"
    sysctls:
      net.core.somaxconn: "2048"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
