# ------------------------------------------------------------------------------
# Ref: https://docs.docker.com/compose/compose-file/
#
# Setup:
# Copy .env.example to .env and modify values as required.
# docker-compose down
# docker-compose build
#
# Run Default example:
# docker-compose up -d
#
# HATop usage:
# docker-compose exec haproxy hatop --help
# docker-compose exec haproxy hatop -s /var/lib/haproxy/stats-1 -i 1
# docker-compose exec haproxy hatop -s /var/lib/haproxy/stats-2 -i 1
# docker-compose exec haproxy hatop -s /var/lib/haproxy/stats-3 -i 1
# docker-compose exec haproxy hatop -s /var/lib/haproxy/stats-4 -i 1
# ------------------------------------------------------------------------------
version: "3.0"
networks:
  tier1:
    driver: "bridge"
  tier3:
    driver: "bridge"
    internal: true
  tier4:
    driver: "bridge"
    internal: true
services:
  haproxy:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: "jdeathe/centos-ssh-haproxy:latest"
    environment:
      HAPROXY_SSL_CERTIFICATE: "${HAPROXY_SSL_CERTIFICATE}"
      HAPROXY_CONFIG: "${HAPROXY_CONFIG}"
      HAPROXY_HOST_NAMES: "${HAPROXY_HOST_NAMES}"
    networks:
      - "tier1"
      - "tier3"
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    sysctls:
      net.core.somaxconn: "32768"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
    tty: true
    ulimits:
      memlock: 82000
      nofile:
        soft: 524288
        hard: 1048576
      nproc: 65535
    volumes:
      # Emulate docker swarm secrets
      - "${PWD}/test/fixture/secrets:/var/run/secrets:ro"
  apache-php1:
    depends_on:
      - "memcached"
    environment:
      APACHE_CUSTOM_LOG_LOCATION: "/dev/stdout"
      APACHE_ERROR_LOG_LOCATION: "/dev/stderr"
      APACHE_LOAD_MODULES: "rewrite_module"
      APACHE_MOD_SSL_ENABLED: "false"
      APACHE_MPM: "event"
      APACHE_SERVER_ALIAS: "app.local"
      APACHE_SERVER_NAME: "www.app.local"
      PHP_OPTIONS_SESSION_SAVE_HANDLER: "memcached"
      PHP_OPTIONS_SESSION_SAVE_PATH: "memcached:11211"
    image: "jdeathe/centos-ssh-apache-php:2.4.0"
    networks:
      tier3:
        aliases:
          - "apache-php.1"
          - "httpd_1"
      tier4:
    restart: "always"
    sysctls:
      net.core.somaxconn: "2048"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
  apache-php2:
    depends_on:
      - "memcached"
    environment:
      APACHE_CUSTOM_LOG_LOCATION: "/dev/stdout"
      APACHE_ERROR_LOG_LOCATION: "/dev/stderr"
      APACHE_LOAD_MODULES: "rewrite_module"
      APACHE_MOD_SSL_ENABLED: "false"
      APACHE_MPM: "event"
      APACHE_SERVER_ALIAS: "app.local"
      APACHE_SERVER_NAME: "www.app.local"
      PHP_OPTIONS_SESSION_SAVE_HANDLER: "memcached"
      PHP_OPTIONS_SESSION_SAVE_PATH: "memcached:11211"
    image: "jdeathe/centos-ssh-apache-php:2.4.0"
    networks:
      tier3:
        aliases:
          - "apache-php.2"
          - "httpd_2"
      tier4:
    restart: "always"
    sysctls:
      net.core.somaxconn: "2048"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
  memcached:
    image: "jdeathe/centos-ssh-memcached:1.3.1"
    environment:
      MEMCACHED_CACHESIZE: "32"
      MEMCACHED_MAXCONN: "2048"
    networks:
      - "tier4"
    restart: "always"
    sysctls:
      net.core.somaxconn: "2048"
