#!/usr/bin/env bash

HAPROXY=/usr/sbin/haproxy
NICE=/bin/nice
SYSCTL=/usr/sbin/sysctl

DAEMON_OPTS="
 -db
 -f ${HAPROXY_CONFIG:-/etc/haproxy/haproxy.cfg}
"

NICENESS=15

${SYSCTL} -p

# ulimit settings require docker containers to be run with --privileged
# https://github.com/dotcloud/docker/issues/4717
# ulimit -n ${NFILES:-131072}
# ulimit -l ${MEMLOCK:-82000}
# ulimit -u ${NPROCS:-unlimited}

exec ${NICE} \
	-n ${NICENESS} \
	${HAPROXY} \
	${DAEMON_OPTS}