#!/usr/bin/env bash

HAPROXY=/usr/sbin/haproxy
NICE=/bin/nice
SYSCTL=/usr/sbin/sysctl

if [[ ! -f /usr/sbin/sysctl ]] \
	&& [[ -f /sbin/sysctl ]]; then
	SYSCTL=/sbin/sysctl
fi

DAEMON_OPTS="
 -db
 -f ${HAPROXY_CONFIG:-/etc/haproxy/haproxy.cfg}
"

NICENESS=10

${SYSCTL} -p

while true; do
	sleep 0.1
	[[ -e /tmp/haproxy-bootstrap.lock ]] || break
done

exec ${NICE} \
	-n ${NICENESS} \
	${HAPROXY} \
	${DAEMON_OPTS}
