#!/usr/bin/env bash

HAPROXY=/usr/sbin/haproxy
NICE=/usr/bin/nice
SYSCTL=/usr/sbin/sysctl

DAEMON_OPTS="
 -db
 -f ${HAPROXY_CONFIG:-/etc/haproxy/haproxy.cfg}
"

NICENESS=10

${SYSCTL} -p

# ulimit settings require docker containers to be run with --privileged
# ulimit -n ${NFILES:-8388608}
# ulimit -l ${MEMLOCK:-82000}
# ulimit -u ${NPROCS:-unlimited}

exec ${NICE} \
	-n ${NICENESS} \
	${HAPROXY} \
	${DAEMON_OPTS}